<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

<iteamgroup> 
  <Resource include = "imagenes\Lagarto.png.png">
  <Resource include = "imagenes\Papel.png.png">
  <Resource include = "imagenes\Piedra.png.png">
  <Resource include = "imagenes\Spock.png.png">
  <Resource include = "imagenes\Tijeras.png.png">
  <Resource include = "sonidos\Lagarto.wav">
  <Resource include = "sonidos\Papel.wav">
  <Resource include = "sonidos\Piedra.wav">
  <Resource include = "sonidos\Spock.wav">
  <Resource include = "sonidos\Tijeras.wav">


</iteamgroup> 

</Project>
