<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

<itemgroup> 
  <Resource include = "Imagenes\Lagarto.png">
  <Resource include = "magenes\Papel.png">
  <Resource include = "imagenes\Piedra.png">
  <Resource include = "Imagenes\Spock.png">
  <Resource include = "Imagenes\Tijeras.png">
  <Resource include = "sonidos\Lagarto.mp3">
  <Resource include = "sonidos\Papel.mp3">
  <Resource include = "sonidos\Piedra.mp3">
  <Resource include = "sonidos\Spock.mp3">
  <Resource include = "sonidos\Tijeras.mp3">

</itemgroup>
</Project>