<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

<ItemGroup> 
  <Resource Include = "Imagenes\Lagarto.png"/>
  <Resource Include = "magenes\Papel.png"/>
  <Resource Include = "imagenes\Piedra.png"/>
  <Resource Include = "Imagenes\Spock.png"/>
  <Resource Include = "Imagenes\Tijeras.png"/>
  <Resource Include = "sonidos\Lagarto.mp3"/>
  <Resource Include = "sonidos\Papel.mp3"/>
  <Resource Include = "sonidos\Piedra.mp3"/>
  <Resource Include = "sonidos\Spock.mp3"/>
  <Resource Include = "sonidos\Tijeras.mp3"/>
</ItemGroup>
</Project>